#!/usr/bin/env python3

from __future__ import annotations

import importlib.util
import json
import os
from pathlib import Path
import queue
import shlex
import socket
import subprocess
import sys
import tempfile
import threading
import time
import unittest
from typing import Any, Callable
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "codex_managed_gateway",
    ROOT / "utilities" / "codex-managed-gateway.py",
)
assert SPEC and SPEC.loader
GATEWAY = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = GATEWAY
SPEC.loader.exec_module(GATEWAY)

# Request shapes mirror the v2 schema generated by codex-cli 0.146.0 on
# 2026-08-03. This is a gateway transport falsifier, not a real-TUI render test.
APP_SERVER_SCHEMA_FIXTURE = "codex-cli-0.146.0-app-server-v2"


def wait_path(path: Path, timeout: float = 5.0) -> None:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if path.exists():
            return
        time.sleep(0.01)
    raise AssertionError(f"socket did not appear: {path}")


class RpcClient:
    def __init__(self, path: Path) -> None:
        self.websocket = GATEWAY.WebSocket.connect_unix(path)
        self._next_id = 1
        self._pending: dict[tuple[str, Any], queue.Queue[dict[str, Any]]] = {}
        self._messages: list[dict[str, Any]] = []
        self._cv = threading.Condition()
        self._closed = False
        self._reader = threading.Thread(target=self._read_loop, daemon=True)
        self._reader.start()

    def _read_loop(self) -> None:
        try:
            while True:
                value = self.websocket.read_json()
                key = GATEWAY.request_key(value.get("id"))
                with self._cv:
                    if (
                        key in self._pending
                        and ("result" in value or "error" in value)
                    ):
                        self._pending[key].put(value)
                    self._messages.append(value)
                    self._cv.notify_all()
        except (EOFError, OSError, GATEWAY.GatewayError):
            pass
        finally:
            with self._cv:
                self._closed = True
                self._cv.notify_all()

    def request(
        self,
        method: str,
        params: dict[str, Any],
        timeout: float = 5.0,
    ) -> dict[str, Any]:
        request_id = self._next_id
        self._next_id += 1
        key = GATEWAY.request_key(request_id)
        assert key is not None
        response_queue: queue.Queue[dict[str, Any]] = queue.Queue(maxsize=1)
        with self._cv:
            self._pending[key] = response_queue
        self.websocket.write_json(
            {
                "jsonrpc": "2.0",
                "id": request_id,
                "method": method,
                "params": params,
            }
        )
        try:
            response = response_queue.get(timeout=timeout)
        finally:
            with self._cv:
                self._pending.pop(key, None)
        if "error" in response:
            raise AssertionError(f"{method} failed: {response['error']}")
        return response["result"]

    def notify(self, method: str, params: dict[str, Any]) -> None:
        self.websocket.write_json(
            {"jsonrpc": "2.0", "method": method, "params": params}
        )

    def respond(self, request_id: Any, result: dict[str, Any]) -> None:
        self.websocket.write_json(
            {"jsonrpc": "2.0", "id": request_id, "result": result}
        )

    def wait_for(
        self,
        predicate: Callable[[dict[str, Any]], bool],
        timeout: float = 5.0,
    ) -> dict[str, Any]:
        deadline = time.monotonic() + timeout
        with self._cv:
            while True:
                for value in self._messages:
                    if predicate(value):
                        return value
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    raise AssertionError("message wait timed out")
                if self._closed:
                    raise AssertionError("client closed while waiting")
                self._cv.wait(min(remaining, 0.1))

    def close(self) -> None:
        self.websocket.close()
        self._reader.join(timeout=2)


class FakeAppServer:
    def __init__(self, path: Path) -> None:
        self.path = path
        self.listener = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        self.listener.bind(str(path))
        self.listener.listen(4)
        self.stop = threading.Event()
        self.lock = threading.Lock()
        self.messages: list[dict[str, Any]] = []
        self.connections = 0
        self.start_count = 0
        self.steer_count = 0
        self.approval_responses: list[dict[str, Any]] = []
        self.hold_start = False
        self.reject_steer = False
        self.start_received = threading.Event()
        self.release_start = threading.Event()
        self.hold_thread_start = False
        self.thread_start_received = threading.Event()
        self.release_thread_start = threading.Event()
        self.current: Any = None
        self.next_start_id = "thread-1"
        self.next_fork_id = "thread-2"
        self.thread = threading.Thread(target=self._accept_loop, daemon=True)
        self.thread.start()

    def _accept_loop(self) -> None:
        while not self.stop.is_set():
            try:
                connection, _ = self.listener.accept()
            except OSError:
                return
            with self.lock:
                self.connections += 1
            try:
                websocket = GATEWAY.WebSocket.accept(connection)
                self.current = websocket
                self._serve(websocket)
            except (EOFError, OSError, GATEWAY.GatewayError):
                pass
            finally:
                self.current = None
                try:
                    websocket.close()
                except (NameError, OSError):
                    connection.close()

    def _serve(self, websocket: Any) -> None:
        while not self.stop.is_set():
            message = websocket.read_json()
            with self.lock:
                self.messages.append(message)
            method = message.get("method")
            if method == "initialize":
                websocket.write_json(
                    {
                        "jsonrpc": "2.0",
                        "id": message["id"],
                        "result": {"serverInfo": {"name": "fake"}},
                    }
                )
            elif method == "initialized":
                continue
            elif method == "thread/start":
                self.thread_start_received.set()
                if self.hold_thread_start:
                    self.release_thread_start.wait(5)
                websocket.write_json(
                    {
                        "jsonrpc": "2.0",
                        "id": message["id"],
                        "result": {"thread": {"id": self.next_start_id}},
                    }
                )
            elif method == "thread/resume":
                params = message.get("params") or {}
                resumed = params.get("threadId") or self.next_start_id
                websocket.write_json(
                    {
                        "jsonrpc": "2.0",
                        "id": message["id"],
                        "result": {"thread": {"id": resumed}},
                    }
                )
            elif method == "thread/fork":
                websocket.write_json(
                    {
                        "jsonrpc": "2.0",
                        "id": message["id"],
                        "result": {"thread": {"id": self.next_fork_id}},
                    }
                )
            elif method == "turn/start":
                with self.lock:
                    self.start_count += 1
                    ordinal = self.start_count
                self.start_received.set()
                if self.hold_start:
                    self.release_start.wait(5)
                turn = {
                    "id": f"turn-{ordinal}",
                    "items": [],
                    "status": "inProgress",
                }
                websocket.write_json(
                    {
                        "jsonrpc": "2.0",
                        "id": message["id"],
                        "result": {"turn": turn},
                    }
                )
                websocket.write_json(
                    {
                        "jsonrpc": "2.0",
                        "method": "turn/started",
                        "params": {"threadId": "thread-1", "turn": turn},
                    }
                )
            elif method == "turn/steer":
                with self.lock:
                    self.steer_count += 1
                if self.reject_steer:
                    websocket.write_json(
                        {
                            "jsonrpc": "2.0",
                            "id": message["id"],
                            "error": {
                                "code": -32011,
                                "message": "active turn is not steerable",
                            },
                        }
                    )
                else:
                    websocket.write_json(
                        {
                            "jsonrpc": "2.0",
                            "id": message["id"],
                            "result": {
                                "turnId": message["params"]["expectedTurnId"]
                            },
                        }
                    )
            elif "id" in message and (
                "result" in message or "error" in message
            ):
                with self.lock:
                    self.approval_responses.append(message)
            elif "id" in message:
                websocket.write_json(
                    {
                        "jsonrpc": "2.0",
                        "id": message["id"],
                        "result": {},
                    }
                )

    def emit_approval(self) -> None:
        deadline = time.monotonic() + 5
        while self.current is None and time.monotonic() < deadline:
            time.sleep(0.01)
        if self.current is None:
            raise AssertionError("no upstream client")
        self.current.write_json(
            {
                "jsonrpc": "2.0",
                "id": 900,
                "method": "item/commandExecution/requestApproval",
                "params": {
                    "threadId": "thread-1",
                    "turnId": "turn-approval",
                    "itemId": "item-approval",
                    "reason": "fixture",
                },
            }
        )

    def emit_user_input(
        self,
        request_id: Any,
        *,
        thread_id: str = "thread-1",
        question: str = "PRIVATE QUESTION",
    ) -> dict[str, Any]:
        deadline = time.monotonic() + 5
        while self.current is None and time.monotonic() < deadline:
            time.sleep(0.01)
        if self.current is None:
            raise AssertionError("no upstream client")
        message = {
            "jsonrpc": "2.0",
            "id": request_id,
            "method": "item/tool/requestUserInput",
            "params": {
                "threadId": thread_id,
                "turnId": "turn-question",
                "itemId": "item-question",
                "questions": [
                    {
                        "id": "choice",
                        "header": "Decision",
                        "question": question,
                        "options": [
                            {
                                "label": "Proceed",
                                "description": "PRIVATE OPTION",
                            }
                        ],
                    }
                ],
            },
        }
        self.current.write_json(message)
        return message

    def emit_resolved(self, thread_id: str, request_id: Any) -> dict[str, Any]:
        if self.current is None:
            raise AssertionError("no upstream client")
        message = {
            "jsonrpc": "2.0",
            "method": "serverRequest/resolved",
            "params": {"threadId": thread_id, "requestId": request_id},
        }
        self.current.write_json(message)
        return message

    def counts(self) -> tuple[int, int]:
        with self.lock:
            return self.start_count, self.steer_count

    def complete_turn(
        self, turn_id: str = "turn-1", status: str = "completed"
    ) -> None:
        deadline = time.monotonic() + 5
        while self.current is None and time.monotonic() < deadline:
            time.sleep(0.01)
        if self.current is None:
            raise AssertionError("no upstream client")
        self.current.write_json(
            {
                "jsonrpc": "2.0",
                "method": "turn/completed",
                "params": {
                    "threadId": "thread-1",
                    "turn": {
                        "id": turn_id,
                        "items": [],
                        "status": status,
                    },
                },
            }
        )

    def methods(self) -> list[str]:
        with self.lock:
            return [
                str(value.get("method"))
                for value in self.messages
                if value.get("method")
            ]

    def close(self) -> None:
        self.stop.set()
        if self.current is not None:
            self.current.close()
        self.listener.close()
        self.thread.join(timeout=2)


def control(path: Path, value: dict[str, Any]) -> dict[str, Any]:
    connection = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    connection.settimeout(10)
    connection.connect(str(path))
    connection.sendall((GATEWAY.canonical(value) + "\n").encode())
    data = bytearray()
    while b"\n" not in data:
        chunk = connection.recv(4096)
        if not chunk:
            break
        data.extend(chunk)
    connection.close()
    return json.loads(bytes(data).split(b"\n", 1)[0])


def receipt_request(
    batch: str = "batch-1", thread_id: str = "thread-1"
) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "op": "deliver",
        "thread_id": thread_id,
        "parent_attempt_id": "att-parent",
        "sealed_batch_id": batch,
        "receipt": {
            "schema_version": 2,
            "state": "ready",
            "parent_attempt_id": "att-parent",
            "job_registry": str(Path(__file__).resolve()),
            "delivery_classification": "success",
            "delivery_timing": GATEWAY.delivery_timing_fields(),
            "children": [
                {
                    "attempt_id": f"att-{batch}",
                    "status": "done",
                    "readiness": "ready",
                    "reason": "registry-closed",
                    "required_action": "advance-completed",
                    "harness": "codex",
                    "delivery_classification": "success",
                }
            ],
        },
    }


class ManagedGatewayTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.upstream = self.root / "upstream.sock"
        self.front = self.root / "front.sock"
        self.control = self.root / "control.sock"
        self.ledger = self.root / "ledger.json"
        self.trace = self.root / "trace.jsonl"
        self.interactions = self.root / "interactions"
        self.interaction_env = mock.patch.dict(
            os.environ,
            {"FLEET_INTERACTION_STATE_DIR": str(self.interactions)},
            clear=False,
        )
        self.interaction_env.start()
        self.server = FakeAppServer(self.upstream)
        self.gateway = GATEWAY.ManagedGateway(
            listen_path=self.front,
            upstream_path=self.upstream,
            control_path=self.control,
            ledger_path=self.ledger,
            trace_path=self.trace,
        )
        self.gateway_thread = threading.Thread(
            target=self.gateway.serve_forever, daemon=True
        )
        self.gateway_thread.start()
        wait_path(self.front)
        wait_path(self.control)
        self.client = self._connect_client()

    def _connect_client(self) -> RpcClient:
        client = RpcClient(self.front)
        client.request(
            "initialize",
            {
                "clientInfo": {
                    "name": "managed-gateway-test",
                    "version": "1",
                },
                "capabilities": {"experimentalApi": True},
            },
        )
        client.notify("initialized", {})
        client.request("thread/start", {})
        deadline = time.monotonic() + 5
        while time.monotonic() < deadline:
            status = control(
                self.control,
                {"schema_version": 1, "op": "status"},
            )
            if status.get("thread_id") == "thread-1":
                return client
            time.sleep(0.01)
        raise AssertionError("gateway did not learn thread")

    def tearDown(self) -> None:
        self.client.close()
        self.gateway.close()
        self.server.close()
        self.gateway_thread.join(timeout=2)
        self.interaction_env.stop()

    def wait_interaction(
        self, thread_id: str, present: bool, timeout: float = 5.0
    ) -> dict[str, Any] | None:
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            value = GATEWAY.fleet_interaction.read_wait(thread_id, "codex")
            if (value is not None) == present:
                return value
            time.sleep(0.01)
        raise AssertionError(
            f"interaction marker did not become {'present' if present else 'absent'}"
        )

    def test_status_proves_witnessed_fork_lineage(self) -> None:
        result = self.client.request(
            "thread/fork", {"threadId": "thread-1"}
        )
        self.assertEqual(result["thread"]["id"], "thread-2")
        status = control(
            self.control, {"schema_version": 1, "op": "status"}
        )
        self.assertEqual(status["thread_id"], "thread-2")
        self.assertEqual(status["thread_ancestors"], ["thread-1"])
        self.assertEqual(status["binding_source"], "fork")

    def test_sibling_thread_start_does_not_move_binding(self) -> None:
        self.server.next_start_id = "thread-sibling"
        self.client.request("thread/start", {})
        status = control(
            self.control, {"schema_version": 1, "op": "status"}
        )
        self.assertEqual(status["thread_id"], "thread-1")
        self.assertEqual(status["binding_source"], "initial")
        self.assertEqual(status["sibling_thread_ids"], ["thread-sibling"])
        self.assertEqual(status["witnessed_thread_id"], "thread-sibling")

    def test_exact_same_thread_resume_is_accepted(self) -> None:
        self.client.request("thread/resume", {"threadId": "thread-1"})
        status = control(
            self.control, {"schema_version": 1, "op": "status"}
        )
        self.assertEqual(status["thread_id"], "thread-1")
        self.assertEqual(status["binding_source"], "resume")

    def test_resume_of_different_id_is_rejected_as_sibling(self) -> None:
        self.client.request("thread/resume", {"threadId": "thread-other"})
        status = control(
            self.control, {"schema_version": 1, "op": "status"}
        )
        self.assertEqual(status["thread_id"], "thread-1")
        self.assertEqual(status["binding_source"], "initial")
        self.assertIn("thread-other", status["sibling_thread_ids"])

    def test_fork_of_non_binding_thread_is_rejected(self) -> None:
        self.server.next_start_id = "thread-sibling"
        self.client.request("thread/start", {})
        self.server.next_fork_id = "thread-sibling-fork"
        self.client.request("thread/fork", {"threadId": "thread-sibling"})
        status = control(
            self.control, {"schema_version": 1, "op": "status"}
        )
        self.assertEqual(status["thread_id"], "thread-1")
        self.assertEqual(status["binding_source"], "initial")
        self.assertIn("thread-sibling-fork", status["sibling_thread_ids"])

    def test_concurrent_probes_and_deliveries_converge_on_one_binding(
        self,
    ) -> None:
        self.server.next_start_id = "thread-sibling"
        self.server.next_fork_id = "thread-2"
        ready = threading.Barrier(5)
        results: dict[str, Any] = {}
        results_lock = threading.Lock()
        snapshots: list[dict[str, Any]] = []

        def sibling_start() -> None:
            ready.wait()
            results["sibling"] = self.client.request("thread/start", {})

        def fork() -> None:
            ready.wait()
            results["fork"] = self.client.request(
                "thread/fork", {"threadId": "thread-1"}
            )

        def probe_status() -> None:
            ready.wait()
            for _ in range(25):
                snapshot = control(
                    self.control, {"schema_version": 1, "op": "status"}
                )
                with results_lock:
                    snapshots.append(snapshot)

        def deliver_sibling() -> None:
            ready.wait()
            results["deliver_sibling"] = control(
                self.control,
                receipt_request("batch-sibling", "thread-sibling"),
            )

        def deliver_binding() -> None:
            ready.wait()
            results["deliver_binding"] = control(
                self.control, receipt_request("batch-binding", "thread-1")
            )

        threads = [
            threading.Thread(target=sibling_start),
            threading.Thread(target=fork),
            threading.Thread(target=probe_status),
            threading.Thread(target=deliver_sibling),
            threading.Thread(target=deliver_binding),
        ]
        for thread in threads:
            thread.start()
        for thread in threads:
            thread.join(timeout=5)
            self.assertFalse(thread.is_alive())

        final = control(
            self.control, {"schema_version": 1, "op": "status"}
        )
        self.assertEqual(final["thread_id"], "thread-2")
        self.assertEqual(final["binding_source"], "fork")
        self.assertIn("thread-sibling", final["sibling_thread_ids"])

        # No probe ever observed a binding outside the two legitimate
        # values (pre-fork "thread-1", post-fork "thread-2") — the lock
        # around binding mutation rules out any interleaved/torn value.
        for snapshot in snapshots:
            self.assertIn(snapshot["thread_id"], {"thread-1", "thread-2"})

        # The sibling thread never owns the binding at any point in the
        # race, so its delivery is unconditionally rejected.
        self.assertEqual(results["deliver_sibling"]["status"], "rejected")
        self.assertEqual(
            results["deliver_sibling"]["reason"],
            "thread-not-owned-by-current-tui",
        )

        # A delivery explicitly addressed to "thread-1" either lands
        # before the fork advances the binding (accepted) or after
        # (rejected as no longer the binding) — never anything else, and
        # never accepted once the binding has moved off "thread-1".
        binding_outcome = results["deliver_binding"]
        self.assertIn(binding_outcome["status"], {"accepted", "rejected"})
        if binding_outcome["status"] == "rejected":
            self.assertEqual(
                binding_outcome["reason"], "thread-not-owned-by-current-tui"
            )

    def test_manual_unwitnessed_turn_start_does_not_move_binding(self) -> None:
        self.client.request(
            "turn/start", {"threadId": "thread-manual-unwitnessed"}
        )
        status = control(
            self.control, {"schema_version": 1, "op": "status"}
        )
        self.assertEqual(status["thread_id"], "thread-1")
        self.assertEqual(status["binding_source"], "initial")

    def test_reconnect_clears_binding_and_lineage(self) -> None:
        self.client.request("thread/fork", {"threadId": "thread-1"})
        self.client.close()
        deadline = time.monotonic() + 5
        while time.monotonic() < deadline:
            status = control(
                self.control, {"schema_version": 1, "op": "status"}
            )
            if status["status"] == "disconnected":
                break
            time.sleep(0.01)
        self.client = self._connect_client()
        status = control(
            self.control, {"schema_version": 1, "op": "status"}
        )
        self.assertEqual(status["thread_id"], "thread-1")
        self.assertEqual(status["thread_ancestors"], [])
        self.assertEqual(status["sibling_thread_ids"], [])
        self.assertEqual(status["binding_source"], "initial")

    def test_foreign_turn_started_does_not_replace_witnessed_ingress(self) -> None:
        assert self.server.current is not None
        notification = {
            "jsonrpc": "2.0",
            "method": "turn/started",
            "params": {
                "threadId": "thread-native-subagent",
                "turn": {
                    "id": "turn-native-subagent",
                    "items": [],
                    "status": "inProgress",
                },
            },
        }
        self.server.current.write_json(notification)
        self.assertEqual(
            self.client.wait_for(lambda value: value == notification),
            notification,
        )
        status = control(
            self.control, {"schema_version": 1, "op": "status"}
        )
        self.assertEqual(status["thread_id"], "thread-1")
        self.assertEqual(status["thread_ancestors"], [])
        self.assertEqual(
            self.gateway._threads["thread-native-subagent"].active_turn_id,
            "turn-native-subagent",
        )

    def test_idle_completion_starts_once_and_duplicate_replays(self) -> None:
        first = control(self.control, receipt_request())
        second = control(self.control, receipt_request())
        self.assertEqual(first["status"], "accepted")
        self.assertEqual(first["action"], "start")
        self.assertFalse(first["replay"])
        self.assertEqual(second["status"], "accepted")
        self.assertTrue(second["replay"])
        self.assertEqual(self.server.counts(), (1, 0))
        starts = [
            value for value in self.server.messages
            if value.get("method") == "turn/start"
        ]
        self.assertEqual(starts[0]["params"]["input"], [])
        encoded = GATEWAY.canonical(starts[0])
        completion_context = starts[0]["params"]["additionalContext"]["hearting-completion"]["value"]
        self.assertIn("AGENT_HARNESS_COMPLETION_V1", encoded)
        self.assertIn("no harvest command; advance the route", encoded)
        self.assertIn('"delivery_classification":"success"', completion_context)
        self.assertIn('"delivery_timing_schema_version":1', completion_context)
        self.assertNotIn("RAW_CHILD", encoded)
        trace = [json.loads(line) for line in self.trace.read_text().splitlines()]
        timing = next(row for row in trace if row.get("event") == "completion-send")
        self.assertEqual(
            set(GATEWAY.DELIVERY_TIMING_POINTS).difference(timing), set()
        )
        self.assertIsInstance(timing["same_thread_resume_ns"], int)

    def test_invalid_delivery_timing_is_rejected_before_upstream(self) -> None:
        before = self.server.counts()
        request = receipt_request("batch-bad-timing")
        request["receipt"]["delivery_timing"].pop("exact_harvest_ns")
        result = control(self.control, request)
        self.assertEqual(result["status"], "rejected")
        self.assertEqual(result["reason"], "receipt-delivery-timing-invalid")
        self.assertEqual(self.server.counts(), before)

    def test_future_delivery_timing_is_rejected_before_upstream(self) -> None:
        before = self.server.counts()
        request = receipt_request("batch-future-timing")
        request["receipt"]["delivery_timing"]["exact_harvest_ns"] = 17
        result = control(self.control, request)
        self.assertEqual(result["status"], "rejected")
        self.assertEqual(result["reason"], "receipt-delivery-timing-phase-invalid")
        self.assertEqual(self.server.counts(), before)

    def test_attention_cannot_request_advance_completed(self) -> None:
        before = self.server.counts()
        request = receipt_request("batch-impossible-action")
        request["receipt"]["delivery_classification"] = "attention"
        request["receipt"]["children"][0]["delivery_classification"] = "attention"
        result = control(self.control, request)
        self.assertEqual(result["status"], "rejected")
        self.assertEqual(result["reason"], "receipt-child-contract-invalid")
        self.assertEqual(self.server.counts(), before)

    def test_actionable_receipt_emits_exact_harvest_command(self) -> None:
        request = receipt_request("batch-open")
        child = request["receipt"]["children"][0]
        child.update(
            {
                "status": "open",
                "reason": "terminal-observed",
                "required_action": "complete-open",
                "delivery_classification": "attention",
            }
        )
        request["receipt"]["delivery_classification"] = "attention"
        result = control(self.control, request)
        self.assertEqual(result["status"], "accepted")
        start = next(
            value for value in self.server.messages
            if value.get("method") == "turn/start"
        )
        encoded = GATEWAY.canonical(start)
        self.assertIn(
            "harvest --jobs "
            + str(Path(__file__).resolve())
            + " --attempt-id att-batch-open --status open --mark-done",
            encoded,
        )

    def test_missing_or_unsafe_job_registry_never_reaches_upstream(self) -> None:
        before = self.server.counts()
        missing = receipt_request("batch-no-jobs")
        missing["receipt"].pop("job_registry")
        self.assertEqual(control(self.control, missing)["status"], "rejected")

        unsafe = receipt_request("batch-unsafe-jobs")
        link = self.root / "jobs-link.log"
        link.symlink_to(Path(__file__).resolve())
        unsafe["receipt"]["job_registry"] = str(link)
        result = control(self.control, unsafe)
        self.assertEqual(result["status"], "rejected")
        self.assertEqual(result["reason"], "receipt-job-registry-unsafe")
        self.assertEqual(self.server.counts(), before)

    def test_rendered_harvest_command_matches_exact_registry_once(self) -> None:
        jobs = self.root / "exact.jobs.log"
        attempt = "att-batch-failed"
        metadata = ",".join(
            (
                "attempt_schema_version=2",
                "dispatch_depth=1",
                "transport=headless",
                "execution_surface=registered-headless",
                "registered_worker=1",
                f"attempt_id={attempt}",
                "harness=codex",
                "failure_class=child-failed",
                "note=dead-worker-fail",
            )
        )
        jobs.write_text(
            f"2026-08-24T00:00:00Z\tdone\t/repo\t/repo\tquick\t{metadata}\n",
            encoding="utf-8",
        )
        request = receipt_request("batch-failed")
        request["receipt"]["job_registry"] = str(jobs)
        request["receipt"]["children"][0].update(
            {
                "attempt_id": attempt,
                "status": "done",
                "required_action": "inspect-done-failure",
            }
        )
        params = GATEWAY.ManagedGateway._context_params(
            "thread-1", request["receipt"], "dlv-fixture"
        )
        context = params["additionalContext"]["hearting-completion"]["value"]
        command = next(line for line in context.splitlines() if " harvest --jobs " in line)
        environment = dict(os.environ)
        for name in (
            "AGENT_DISPATCH_JOBS",
            "AGENT_DISPATCH_ATTEMPT_ID",
            "AGENT_DISPATCH_PARENT_SESSION_ID",
            "AGENT_DISPATCH_COMPLETION_STATE_FILE",
        ):
            environment.pop(name, None)
        result = subprocess.run(
            shlex.split(command),
            text=True,
            capture_output=True,
            env=environment,
            timeout=10,
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn(f"job_registry={jobs}", result.stdout)
        self.assertIn("matched=1", result.stdout)

    def test_active_manual_turn_receipt_steers_without_second_turn(self) -> None:
        self.client.request(
            "turn/start",
            {
                "threadId": "thread-1",
                "input": [{"type": "text", "text": "manual"}],
            },
        )
        result = control(self.control, receipt_request())
        self.assertEqual(result["status"], "accepted")
        self.assertEqual(result["action"], "steer")
        self.assertEqual(self.server.counts(), (1, 1))
        steer = next(
            value for value in self.server.messages
            if value.get("method") == "turn/steer"
        )
        self.assertEqual(steer["params"]["expectedTurnId"], "turn-1")
        self.assertEqual(steer["params"]["input"], [])

    def test_rejected_steer_serializes_one_start_after_manual_turn(self) -> None:
        self.server.reject_steer = True
        self.client.request(
            "turn/start",
            {
                "threadId": "thread-1",
                "input": [{"type": "text", "text": "manual"}],
            },
        )
        outcome: dict[str, Any] = {}

        def completion() -> None:
            outcome.update(control(self.control, receipt_request()))

        worker = threading.Thread(target=completion)
        worker.start()
        deadline = time.monotonic() + 5
        while self.server.counts()[1] != 1 and time.monotonic() < deadline:
            time.sleep(0.01)
        self.assertEqual(self.server.counts(), (1, 1))
        self.assertTrue(worker.is_alive())
        self.server.complete_turn()
        worker.join(timeout=5)
        self.assertFalse(worker.is_alive())
        self.assertEqual(outcome["status"], "accepted")
        self.assertEqual(outcome["action"], "start-after-steer-rejected")
        self.assertEqual(self.server.counts(), (2, 1))
        replay = control(self.control, receipt_request())
        self.assertTrue(replay["replay"])
        self.assertEqual(replay["action"], "start-after-steer-rejected")
        self.assertEqual(self.server.counts(), (2, 1))

    def test_pending_start_race_is_one_start_plus_one_steer(self) -> None:
        self.server.hold_start = True
        barrier = threading.Barrier(3)
        outcomes: dict[str, Any] = {}

        def manual() -> None:
            barrier.wait()
            outcomes["manual"] = self.client.request(
                "turn/start",
                {
                    "threadId": "thread-1",
                    "input": [{"type": "text", "text": "race-manual"}],
                },
            )

        def completion() -> None:
            barrier.wait()
            outcomes["completion"] = control(
                self.control, receipt_request()
            )

        threads = [
            threading.Thread(target=manual),
            threading.Thread(target=completion),
        ]
        for thread in threads:
            thread.start()
        barrier.wait()
        self.assertTrue(self.server.start_received.wait(5))
        time.sleep(0.05)
        self.assertEqual(self.server.counts(), (1, 0))
        self.server.release_start.set()
        for thread in threads:
            thread.join(timeout=5)
            self.assertFalse(thread.is_alive())
        self.assertEqual(outcomes["completion"]["status"], "accepted")
        self.assertEqual(self.server.counts(), (1, 1))
        self.assertEqual(outcomes["manual"]["turn"]["id"], "turn-1")

    def test_approval_only_reaches_tui(self) -> None:
        self.server.emit_approval()
        request = self.client.wait_for(
            lambda value: (
                value.get("method")
                == "item/commandExecution/requestApproval"
            )
        )
        self.client.respond(request["id"], {"decision": "accept"})
        deadline = time.monotonic() + 5
        while (
            not self.server.approval_responses
            and time.monotonic() < deadline
        ):
            time.sleep(0.01)
        self.assertEqual(len(self.server.approval_responses), 1)
        status = control(
            self.control, {"schema_version": 1, "op": "status"}
        )
        self.assertEqual(status["approval_owner"], "tui")
        self.assertEqual(status["upstream_clients"], 1)
        self.assertNotIn(
            "requestApproval",
            self.trace.read_text(encoding="utf-8"),
        )

    def test_request_user_input_traverses_gateway_and_clears_on_response(self) -> None:
        request = self.server.emit_user_input(901)
        received = self.client.wait_for(
            lambda value: value.get("method") == "item/tool/requestUserInput"
            and value.get("id") == 901
        )
        self.assertEqual(received, request)
        marker = self.wait_interaction("thread-1", True)
        assert marker is not None
        self.assertEqual(set(marker), GATEWAY.fleet_interaction._ALLOWED_KEYS)
        self.assertEqual(marker["source"], "codex-appserver")

        response = {
            "answers": {"choice": {"selected": ["Proceed"]}}
        }
        self.client.respond(901, response)
        deadline = time.monotonic() + 5
        expected = {"jsonrpc": "2.0", "id": 901, "result": response}
        while expected not in self.server.approval_responses and time.monotonic() < deadline:
            time.sleep(0.01)
        self.assertIn(expected, self.server.approval_responses)
        self.wait_interaction("thread-1", False)
        persisted = "".join(
            path.read_text(encoding="utf-8")
            for path in (self.trace, self.ledger)
            if path.exists()
        )
        self.assertNotIn("PRIVATE QUESTION", persisted)
        self.assertNotIn("PRIVATE OPTION", persisted)

    def test_typed_ids_remain_distinct_until_each_response(self) -> None:
        self.server.emit_user_input(17)
        first_marker = self.wait_interaction("thread-1", True)
        assert first_marker is not None
        time.sleep(0.01)
        self.server.emit_user_input("17")
        self.client.wait_for(
            lambda value: value.get("method") == "item/tool/requestUserInput"
            and value.get("id") == 17
            and not isinstance(value.get("id"), bool)
        )
        self.client.wait_for(
            lambda value: value.get("method") == "item/tool/requestUserInput"
            and value.get("id") == "17"
        )
        self.wait_interaction("thread-1", True)
        self.client.respond(17, {"answers": {}})
        deadline = time.monotonic() + 5
        remaining_marker = None
        while time.monotonic() < deadline:
            candidate = GATEWAY.fleet_interaction.read_wait(
                "thread-1", "codex"
            )
            if (
                candidate is not None
                and candidate["waiting_since"] > first_marker["waiting_since"]
            ):
                remaining_marker = candidate
                break
            time.sleep(0.01)
        assert remaining_marker is not None
        self.client.respond("17", {"answers": {}})
        self.wait_interaction("thread-1", False)

    def test_resolved_notification_uses_thread_and_typed_request_id(self) -> None:
        first = self.server.emit_user_input("shared", thread_id="thread-1")
        second = self.server.emit_user_input("shared", thread_id="thread-2")
        for expected in (first, second):
            received = self.client.wait_for(
                lambda value, expected=expected: value == expected
            )
            self.assertEqual(received, expected)
        self.wait_interaction("thread-1", True)
        self.wait_interaction("thread-2", True)

        # A methodless response cannot safely choose between colliding ids.
        self.client.respond("shared", {"answers": {}})
        self.wait_interaction("thread-1", True)
        self.wait_interaction("thread-2", True)
        resolved = self.server.emit_resolved("thread-1", "shared")
        self.assertEqual(
            self.client.wait_for(lambda value: value == resolved), resolved
        )
        self.wait_interaction("thread-1", False)
        self.wait_interaction("thread-2", True)
        self.server.emit_resolved("thread-foreign", "shared")
        self.wait_interaction("thread-2", True)
        self.server.emit_resolved("thread-2", "shared")
        self.wait_interaction("thread-2", False)

    def test_interruption_and_disconnect_clear_only_gateway_owned_state(self) -> None:
        self.server.emit_user_input(902)
        self.wait_interaction("thread-1", True)
        GATEWAY.fleet_interaction.set_wait(
            "thread-1",
            "codex",
            "approval",
            "codex-permissionrequest",
        )
        self.client.respond(902, {"answers": {}})
        marker = self.wait_interaction("thread-1", True)
        assert marker is not None
        self.assertEqual(marker["source"], "codex-permissionrequest")

        GATEWAY.fleet_interaction.clear_wait("thread-1", "codex")
        self.server.emit_user_input(903)
        self.wait_interaction("thread-1", True)
        self.server.complete_turn(status="interrupted")
        self.wait_interaction("thread-1", False)

        self.server.emit_user_input(904)
        self.wait_interaction("thread-1", True)
        self.client.close()
        self.wait_interaction("thread-1", False)
        self.client = self._connect_client()

    def test_interaction_observation_failures_do_not_change_forwarding(self) -> None:
        with mock.patch.object(
            GATEWAY.fleet_interaction,
            "set_wait",
            side_effect=RuntimeError("fixture"),
        ):
            request = self.server.emit_user_input(905)
            self.assertEqual(
                self.client.wait_for(lambda value: value == request), request
            )
        self.client.respond(905, {"answers": {}})
        deadline = time.monotonic() + 5
        while not any(
            value.get("id") == 905
            for value in self.server.approval_responses
        ) and time.monotonic() < deadline:
            time.sleep(0.01)
        self.assertTrue(
            any(value.get("id") == 905 for value in self.server.approval_responses)
        )

        request = self.server.emit_user_input(907)
        self.assertEqual(
            self.client.wait_for(lambda value: value == request), request
        )
        self.wait_interaction("thread-1", True)
        with mock.patch.object(
            GATEWAY.fleet_interaction,
            "clear_wait",
            side_effect=RuntimeError("fixture"),
        ):
            self.client.respond(907, {"answers": {}})
            deadline = time.monotonic() + 5
            while not any(
                value.get("id") == 907
                for value in self.server.approval_responses
            ) and time.monotonic() < deadline:
                time.sleep(0.01)
            self.assertTrue(
                any(
                    value.get("id") == 907
                    for value in self.server.approval_responses
                )
            )
            self.wait_interaction("thread-1", True)
        GATEWAY.fleet_interaction.clear_wait("thread-1", "codex")

    def test_unsafe_thread_identity_is_forwarded_but_never_persisted(self) -> None:
        request = self.server.emit_user_input(906, thread_id="../unsafe")
        self.assertEqual(
            self.client.wait_for(lambda value: value == request), request
        )
        self.assertEqual(self.gateway._appserver_requests, {})
        self.assertFalse(self.interactions.exists())

    def test_foreign_or_incomplete_receipt_never_reaches_upstream(self) -> None:
        before = self.server.counts()
        foreign = receipt_request()
        foreign["thread_id"] = "thread-foreign"
        result = control(self.control, foreign)
        self.assertEqual(result["status"], "rejected")
        incomplete = receipt_request("batch-incomplete")
        incomplete["receipt"]["children"][0]["readiness"] = "pending"
        result = control(self.control, incomplete)
        self.assertEqual(result["status"], "rejected")
        self.assertEqual(self.server.counts(), before)

    def test_disconnect_fails_closed_then_reconnects(self) -> None:
        self.client.close()
        deadline = time.monotonic() + 5
        while time.monotonic() < deadline:
            status = control(
                self.control,
                {"schema_version": 1, "op": "status"},
            )
            if status["status"] == "disconnected":
                break
            time.sleep(0.01)
        result = control(self.control, receipt_request("batch-offline"))
        self.assertEqual(result["status"], "retryable")
        self.client = self._connect_client()
        result = control(self.control, receipt_request("batch-reconnected"))
        self.assertEqual(result["status"], "accepted")
        self.assertEqual(self.server.connections, 2)


class EstablishFromEmptyBindingRaceTest(unittest.TestCase):
    """A fresh gateway has no binding yet. An unwitnessed App-Server
    `turn/started` notification (e.g. from a native subagent or any other
    sibling thread) must never establish the parent ingress binding, even
    from empty -- only a gateway-witnessed thread/start (or resume/fork)
    response may do that."""

    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.upstream = self.root / "upstream.sock"
        self.front = self.root / "front.sock"
        self.control = self.root / "control.sock"
        self.ledger = self.root / "ledger.json"
        self.trace = self.root / "trace.jsonl"
        self.interactions = self.root / "interactions"
        self.interaction_env = mock.patch.dict(
            os.environ,
            {"FLEET_INTERACTION_STATE_DIR": str(self.interactions)},
            clear=False,
        )
        self.interaction_env.start()
        self.addCleanup(self.interaction_env.stop)
        self.server = FakeAppServer(self.upstream)
        self.addCleanup(self.server.close)
        self.gateway = GATEWAY.ManagedGateway(
            listen_path=self.front,
            upstream_path=self.upstream,
            control_path=self.control,
            ledger_path=self.ledger,
            trace_path=self.trace,
        )
        self.gateway_thread = threading.Thread(
            target=self.gateway.serve_forever, daemon=True
        )
        self.gateway_thread.start()
        self.addCleanup(self.gateway.close)
        self.addCleanup(lambda: self.gateway_thread.join(timeout=2))
        wait_path(self.front)
        wait_path(self.control)
        self.client = RpcClient(self.front)
        self.addCleanup(self.client.close)
        self.client.request(
            "initialize",
            {
                "clientInfo": {
                    "name": "managed-gateway-test",
                    "version": "1",
                },
                "capabilities": {"experimentalApi": True},
            },
        )
        self.client.notify("initialized", {})

    def test_unwitnessed_sibling_turn_started_cannot_establish_binding_from_empty(
        self,
    ) -> None:
        status = control(self.control, {"schema_version": 1, "op": "status"})
        self.assertEqual(status["thread_id"], "")
        self.assertEqual(status["binding_source"], "")

        self.server.hold_thread_start = True
        start_thread = threading.Thread(
            target=lambda: self.client.request("thread/start", {})
        )
        start_thread.start()
        self.addCleanup(lambda: start_thread.join(timeout=5))
        self.assertTrue(self.server.thread_start_received.wait(5))

        deadline = time.monotonic() + 5
        while self.server.current is None and time.monotonic() < deadline:
            time.sleep(0.01)
        assert self.server.current is not None
        notification = {
            "jsonrpc": "2.0",
            "method": "turn/started",
            "params": {
                "threadId": "thread-native-subagent",
                "turn": {
                    "id": "turn-native-subagent",
                    "items": [],
                    "status": "inProgress",
                },
            },
        }
        self.server.current.write_json(notification)
        self.assertEqual(
            self.client.wait_for(lambda value: value == notification),
            notification,
        )

        # The sibling notification was witnessed for per-thread bookkeeping
        # only -- it must not have established the binding while empty.
        status = control(self.control, {"schema_version": 1, "op": "status"})
        self.assertEqual(status["thread_id"], "")
        self.assertEqual(status["binding_source"], "")
        self.assertEqual(status["witnessed_thread_id"], "thread-native-subagent")
        self.assertEqual(
            self.gateway._threads["thread-native-subagent"].active_turn_id,
            "turn-native-subagent",
        )

        # Now release the parent's own witnessed thread/start response and
        # prove it -- and only it -- establishes the binding.
        self.server.release_thread_start.set()
        start_thread.join(timeout=5)
        self.assertFalse(start_thread.is_alive())
        deadline = time.monotonic() + 5
        while time.monotonic() < deadline:
            status = control(
                self.control, {"schema_version": 1, "op": "status"}
            )
            if status.get("thread_id") == "thread-1":
                break
            time.sleep(0.01)
        self.assertEqual(status["thread_id"], "thread-1")
        self.assertEqual(status["binding_source"], "initial")


class ValidateDeliveryStageAdvanceNegotiationTest(unittest.TestCase):
    """SD-110 A-18: a gateway that has not negotiated `accept_stage_advance`
    (default False) validates a receipt exactly as before -- golden-byte
    identical `normalized` output -- and a stray `stage_advance` key on an
    un-negotiated gateway is rejected rather than silently passed through."""

    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        root = Path(self.temp.name)
        self.gateway = GATEWAY.ManagedGateway(
            listen_path=root / "front.sock",
            upstream_path=root / "upstream.sock",
            control_path=root / "control.sock",
            ledger_path=root / "ledger.json",
        )
        self.negotiated_gateway = GATEWAY.ManagedGateway(
            listen_path=root / "front2.sock",
            upstream_path=root / "upstream.sock",
            control_path=root / "control.sock",
            ledger_path=root / "ledger2.json",
            accept_stage_advance=True,
        )

    def _record(self):
        return {
            "schema_version": 1,
            "stage_advance_id": "sadv-" + "0" * 64,
            "route_id": "rt-0000000000000000",
            "route_hash": "sha256:" + "0" * 64,
            "predecessor_node": "plan",
            "predecessor_terminal_attempt_id": "att-plan",
            "successor_node": "execute",
            "successor_attempt_id": "att-execute",
            "claim_key": ["sha256:" + "0" * 64, "execute", 0],
            "brief_template_digest": "sha256:" + "1" * 64,
            "outcome": "advanced",
            "reason": "",
            "registered": True,
            "started": True,
            "child_spawned": True,
        }

    def test_default_gateway_is_byte_identical_to_pre_sd110(self):
        request = receipt_request()
        *_, normalized, _receipt_digest, _delivery_id = self.gateway._validate_delivery(
            request
        )
        self.assertEqual(normalized["schema_version"], 2)
        self.assertNotIn("stage_advance", normalized)
        # SD-119: the chain-advance path exists but a join with no
        # sub-session chain metadata is a no-op -- this receipt never carries
        # a chain key, byte-identical to pre-SD-119.
        sys.path.insert(0, str(ROOT / "utilities"))
        import dispatch_subsession_advance as subsession_advance
        from types import SimpleNamespace

        no_chain = subsession_advance.coordinate_chain_advance_from_joined_rows(
            Path("/nonexistent/jobs.registry"), "att-parent", {
                "att-child": SimpleNamespace(
                    attempt_id="att-child", status="done", metadata={},
                )
            },
        )
        self.assertIsNone(no_chain)
        self.assertNotIn("chain_id", json.dumps(normalized, sort_keys=True))

    def test_unnegotiated_gateway_rejects_stray_stage_advance_key(self):
        request = receipt_request()
        request["receipt"] = {
            **request["receipt"],
            "schema_version": GATEWAY.STAGE_ADVANCE_SCHEMA_VERSION,
            "stage_advance": self._record(),
        }
        with self.assertRaises(GATEWAY.GatewayError):
            self.gateway._validate_delivery(request)

    def test_negotiated_gateway_attaches_stage_advance_block(self):
        request = receipt_request()
        record = self._record()
        request["receipt"] = {
            **request["receipt"],
            "schema_version": GATEWAY.STAGE_ADVANCE_SCHEMA_VERSION,
            "stage_advance": record,
        }
        *_, normalized, _receipt_digest, _delivery_id = (
            self.negotiated_gateway._validate_delivery(request)
        )
        self.assertEqual(normalized["schema_version"], 3)
        self.assertEqual(normalized["stage_advance"], record)

    def test_negotiated_gateway_still_accepts_v2_receipts(self):
        request = receipt_request()
        *_, normalized, _receipt_digest, _delivery_id = (
            self.negotiated_gateway._validate_delivery(request)
        )
        self.assertEqual(normalized["schema_version"], 2)
        self.assertNotIn("stage_advance", normalized)


class DeliveryLedgerProjectionTest(unittest.TestCase):
    """SD-111 P5 (A-23, `structural`): single public entry point onto the
    ledger. This asserts design enforcement -- `_transition` is private,
    `project_from_pending_delivery` is the only public state-transition
    method, and a malformed record leaves the ledger unchanged -- not the
    absence of a second independent commit path anywhere in the file
    (plan §7.1-4 forbids reporting this as "measured PASS")."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory(prefix="sd111-p5-")
        self.ledger_path = Path(self._tmp.name) / "ledger.json"

    def tearDown(self):
        self._tmp.cleanup()

    def _record(self, **overrides):
        base = {
            "delivery_id": "delivery-" + "a" * 32,
            "state": "pending",
            "receipt_digest": "d" * 64,
            "parent_attempt_id": "att-" + "b" * 32,
            "receipt": {"job_registry": "/tmp/sd111p5/jobs.log"},
        }
        base.update(overrides)
        return base

    def test_transition_is_private_and_projection_is_the_only_public_entry_point(self):
        self.assertFalse(hasattr(GATEWAY.DeliveryLedger, "transition"))
        self.assertTrue(hasattr(GATEWAY.DeliveryLedger, "_transition"))
        public_transition_methods = [
            name
            for name in vars(GATEWAY.DeliveryLedger)
            if not name.startswith("_")
            and callable(getattr(GATEWAY.DeliveryLedger, name))
            and name not in {"get"}
        ]
        self.assertEqual(public_transition_methods, ["project_from_pending_delivery"])

    def test_static_scan_no_ledger_mutation_outside_transition(self):
        """`self.value[...] = ...` (the only line that actually mutates ledger
        state) appears exactly once in the whole file, inside `_transition` --
        i.e. there is no second, independent write path."""

        source = (ROOT / "utilities" / "codex-managed-gateway.py").read_text(
            encoding="utf-8"
        )
        lines = source.splitlines()
        mutation_lines = [
            i for i, line in enumerate(lines)
            if 'self.value["deliveries"][delivery_id] = row' in line
        ]
        self.assertEqual(len(mutation_lines), 1)

    def test_projection_pending_state_maps_to_prepared(self):
        ledger = GATEWAY.DeliveryLedger(self.ledger_path)
        record = self._record(state="pending")
        row = ledger.project_from_pending_delivery(record)
        self.assertEqual(row["state"], "prepared")
        self.assertEqual(ledger.get(record["delivery_id"])["state"], "prepared")

    def test_projection_state_map_covers_every_pending_delivery_state(self):
        ledger = GATEWAY.DeliveryLedger(self.ledger_path)

        # pending -> prepared, on a fresh delivery_id (the ledger's own
        # `None -> "prepared"` legal entry transition).
        did_a = "delivery-" + "1" * 32
        row = ledger.project_from_pending_delivery(self._record(delivery_id=did_a, state="pending"))
        self.assertEqual(row["state"], "prepared")

        # claimed -> prepared, a fresh id (both pending-delivery states
        # project onto the ledger's one "not yet sent" state).
        did_b = "delivery-" + "2" * 32
        row = ledger.project_from_pending_delivery(self._record(delivery_id=did_b, state="claimed"))
        self.assertEqual(row["state"], "prepared")

        # sent-ambiguous -> sent, driven through its legal prior state.
        did_c = "delivery-" + "3" * 32
        ledger.project_from_pending_delivery(self._record(delivery_id=did_c, state="pending"))
        row = ledger.project_from_pending_delivery(self._record(delivery_id=did_c, state="sent-ambiguous"))
        self.assertEqual(row["state"], "sent")

        # acked -> accepted, driven through prepared -> sent -> accepted.
        did_d = "delivery-" + "4" * 32
        ledger.project_from_pending_delivery(self._record(delivery_id=did_d, state="pending"))
        ledger.project_from_pending_delivery(self._record(delivery_id=did_d, state="sent-ambiguous"))
        row = ledger.project_from_pending_delivery(self._record(delivery_id=did_d, state="acked"))
        self.assertEqual(row["state"], "accepted")

        # expired -> rejected, driven through its legal prior state.
        did_e = "delivery-" + "5" * 32
        ledger.project_from_pending_delivery(self._record(delivery_id=did_e, state="pending"))
        row = ledger.project_from_pending_delivery(self._record(delivery_id=did_e, state="expired"))
        self.assertEqual(row["state"], "rejected")

    def test_malformed_record_raises_and_leaves_ledger_unchanged(self):
        ledger = GATEWAY.DeliveryLedger(self.ledger_path)
        ledger.project_from_pending_delivery(self._record(state="pending"))
        before = json.loads(json.dumps(ledger.value))
        with self.assertRaises(GATEWAY.GatewayError):
            ledger.project_from_pending_delivery(self._record(state="not-a-real-state"))
        self.assertEqual(ledger.value, before)
        with self.assertRaises(GATEWAY.GatewayError):
            ledger.project_from_pending_delivery({"delivery_id": "delivery-x", "state": "pending"})
        self.assertEqual(ledger.value, before)
        with self.assertRaises(GATEWAY.GatewayError):
            ledger.project_from_pending_delivery("not-a-dict")
        self.assertEqual(ledger.value, before)

    def test_projection_failure_does_not_persist_a_partial_write(self):
        ledger = GATEWAY.DeliveryLedger(self.ledger_path)
        with self.assertRaises(GATEWAY.GatewayError):
            ledger.project_from_pending_delivery(self._record(state="expired"))
        self.assertFalse(self.ledger_path.exists())


if __name__ == "__main__":
    unittest.main()
